### ISSUE TITLE
wync version bump

### ISSUE THREAD

**Issue by mystica555** [thehaven/haven-overlay#2]
Please update the version

**Comment by thehaven** [comment]
Latest ebuild is 2.0.257 based off the debian bin files which have not yet been updated to 2.0.305. Once that changes (and I notice) I'll update.

For now there is nothing to update to.

**Comment by mystica555** [comment]
Hi Simon;

Unfortunately I tried the precise version you had, and it refuses to allow
me to login with the current Lync release on Azure.  Even the 305 version -
yes the Ubuntu version "runs" but v305 is also will not login with said
Lync on Azure..

I then found the BETA relase
http://fisil.com/linux/wync_ubuntu64_v2.0.328.deb

This version  FINALLY allowed me to login.  Granted, Lync is crap, but hey,
this version at least worked within the scope of "allows me to login, if
not actually see any contacts or participate in any sort of useful group
chat" (a limitation of the Azure implementation - they want to push
godawful Yammer...ugh)

All I wanted was an ircd :\ And this is what the company decided to get
instead...

Thanks,

Mike

**Comment by thehaven** [comment]
Hi Mike, I've just updated and pushed a new update that uses the Ubuntu bin files instead of Debian and therefore is version bumped to 2.0.328. Give it a go and see if that helps, I'm able to log in fine without any issues on both versions against the company Lync server (not Azure based).

These ebuilds are just running the wync supplied bin files so unfortunately I've no access to change any code but hopefully the version bump helps.

Simon
